# Generated by Django 5.0 on 2024-01-08 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='ingredients',
            new_name='ingredient',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='created_at',
        ),
    ]
