# Generated by Django 4.2.6 on 2023-10-13 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_recipe_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='recipe',
            name='added_at',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipes_added_at', to='cookbook.addrecipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipes_added_by', to='cookbook.addrecipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_descriptions', to='cookbook.addrecipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_instructions', to='cookbook.addrecipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_titles', to='cookbook.addrecipe'),
        ),
    ]
