# Generated by Django 4.2.6 on 2023-10-15 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_remove_recipe_created_at_remove_recipe_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='addrecipe',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='addrecipe',
            old_name='instructions',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='addrecipe',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='title',
        ),
        migrations.AddField(
            model_name='addrecipe',
            name='cook_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addrecipe',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='addrecipe',
            name='ingredients',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addrecipe',
            name='number_of_portions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addrecipe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_photos/'),
        ),
        migrations.AddField(
            model_name='addrecipe',
            name='prep_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addrecipe',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addrecipe',
            name='tips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='add_recipe',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='cookbook.addrecipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addrecipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='cookbook.tag'),
        ),
    ]
