# Generated by Django 4.2.6 on 2023-10-15 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0005_tag_rename_title_addrecipe_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tag_name',
        ),
    ]
