# Generated by Django 4.2.6 on 2023-10-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0007_remove_recipe_add_recipe_recipe_added_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='instructions',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_photos/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='cookbook.tag'),
        ),
        migrations.AlterField(
            model_name='addrecipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='add_recipes', to='cookbook.tag'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
