# Generated by Django 4.2.6 on 2023-10-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0008_rename_instructions_recipe_notes_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecipe',
            name='cook_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='addrecipe',
            name='prep_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
