# Generated by Django 4.2.6 on 2023-12-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0011_remove_shoppinglist_recipes_shoppinglist_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='ingredients',
            field=models.TextField(),
        ),
    ]
