# Generated by Django 4.2.6 on 2023-12-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0012_alter_shoppinglist_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplanner',
            name='created_at',
        ),
    ]
