# Generated by Django 5.0 on 2023-12-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0013_remove_mealplanner_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecipe',
            name='cook_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addrecipe',
            name='prep_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
