# Generated by Django 5.0 on 2023-12-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0014_alter_addrecipe_cook_time_alter_addrecipe_prep_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addrecipe',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='addrecipe',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='addrecipe',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='mealplanner',
            name='user',
        ),
        migrations.AlterField(
            model_name='addrecipe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addrecipe',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addrecipe',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='addrecipe',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
