# Generated by Django 5.0 on 2023-12-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0016_favoriterecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrecipe',
            name='favorites_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
