# Generated by Django 5.0 on 2023-12-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0017_addrecipe_favorites_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteRecipe',
            new_name='FavouriteRecipe',
        ),
        migrations.RemoveField(
            model_name='addrecipe',
            name='favorites_count',
        ),
        migrations.AddField(
            model_name='addrecipe',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
